title: TyperTools
description: Photoshop extension for typesetters.
logo: /assets/img/typertools.png
download_url: /builds/typertools-1.3.1.zip
app_version: 1.3.1
author_name: Swirt
author_url: https://telegram.me/swirt
google_analytics: UA-168805410-1
theme: jekyll-theme-minimal
