title: TyperTools
description: Photoshop extension for typesetters.
logo: /assets/img/typertools.png
download_url: /builds/typertools-1.4.7.zip
app_version: 1.4.7
author_name: Swirt
author_url: https://telegram.me/swirt
source_url: https://github.com/Swirt/typertools-src
google_analytics: UA-168805410-1
theme: jekyll-theme-minimal
